backend: 
  name: git-gateway
  branch: master

media_folder: static/assets
public_folder: assets

collections:
  - name: posts
    label: News
    folder: news
    create: true
    fields:
      - { name: title, label: Title }
      - { name: date, label: Date, widget: datetime }
      - { name: body, label: Body, widget: markdown }