backend: 
  name: git-gateway
  branch: master
  commit_messages:
    create: 'Create {{collection}} “{{slug}}”'
    update: 'Update {{collection}} “{{slug}}”'
    delete: 'Delete {{collection}} “{{slug}}”'
    uploadMedia: '[skip ci] Upload “{{path}}”'
    deleteMedia: '[skip ci] Delete “{{path}}”'

media_folder: content/media
public_folder: ../media

media_library:
  name: cloudinary
  config:
    cloud_name: drgctrdk4
    api_key: 855765796578929

collections:
  - name: posts
    label: News
    folder: content/news
    create: true
    fields:
      - { name: templateKey, label: Template Key, widget: hidden, default: news-post }
      - { name: title, label: Title, required: false }
      - { name: dateNewsFormat, label: Date, widget: datetime }
      - { name: body, label: Body, required: false, widget: markdown }

  - name: courses
    label: Courses
    folder: content/courses
    create: true
    fields:
      - { name: templateKey, label: Template Key, widget: hidden, default: course-page }
      - { name: title, label: Title, hint: "URL path to course page - Must be unique!" }
      - { name: displayTitle, label: Display Title, required: true, widget: string }
      - { name: eventCourse, label: Event Course, widget: boolean, hint: Select to add to Event Courses page, required: false, default: false }
      - { name: courseDesign, label: Course Design, widget: boolean, hint: Select to add to Course Design page, required: false, default: false }
      - { name: site, label: Site/Park, hint: "Site of the course (park name)", required: false, widget: string }
      - { name: location, label: Location, hint: "Location of park - format: City, State", required: false, widget: string }
      - { name: address, label: Address, required: false, widget: string }
      - { name: coursesDescription, label: Courses Page Description, hint: "Max Characters...", required: false, widget: string }
      - { name: coursesImage, label: Courses Page Image, hint: "465px x 300px", required: false, widget: image, default: "" }
      - { name: courseHeroImage, label: Course Page Hero, hint: "Height 360px - image will fill space.", required: false, widget: image, default: "" }
      - { name: guideDownload, label: Caddy guide download link, hint: "Single file caddy guide", required: false, widget: image, default: "" }
      - { name: date, label: Date, required: false, widget: datetime }
      - { name: hole01, label: Hole 1, required: false, widget: image, hint: "File names must be alphabetical starting with 'Tee_Signs_'. Example: Tee_Signs_belton_01.jpg"  , default: "" }
      - { name: hole02, label: Hole 2, required: false, widget: image, default: "" }
      - { name: hole03, label: Hole 3, required: false, widget: image, default: "" }
      - { name: hole04, label: Hole 4, required: false, widget: image, default: "" }
      - { name: hole05, label: Hole 5, required: false, widget: image, default: "" }
      - { name: hole06, label: Hole 6, required: false, widget: image, default: "" }
      - { name: hole07, label: Hole 7, required: false, widget: image, default: "" }
      - { name: hole08, label: Hole 8, required: false, widget: image, default: "" }
      - { name: hole09, label: Hole 9, required: false, widget: image, default: "" }
      - { name: hole10, label: Hole 10, required: false, widget: image, default: "" }
      - { name: hole11, label: Hole 11, required: false, widget: image, default: "" }
      - { name: hole12, label: Hole 12, required: false, widget: image, default: "" }
      - { name: hole13, label: Hole 13, required: false, widget: image, default: "" }
      - { name: hole14, label: Hole 14, required: false, widget: image, default: "" }
      - { name: hole15, label: Hole 15, required: false, widget: image, default: "" }
      - { name: hole16, label: Hole 16, required: false, widget: image, default: "" }
      - { name: hole17, label: Hole 17, required: false, widget: image, default: "" }
      - { name: hole18, label: Hole 18, required: false, widget: image, default: "" }
      - { name: hole19, label: Hole 19, required: false, widget: image, default: "" }
      - { name: hole20, label: Hole 20, required: false, widget: image, default: "" }
      - { name: body, label: Body, required: false, widget: markdown }

  - name: sponsors
    label: Sponsors
    files:
      - label: Sponsors Page
        name: sponsorsPage
        file: "content/sponsors/sponsors-page.md"
        fields:
          - { label: Template Key, name: templateKey, widget: hidden, default: sponsors-page }
          - { label: Date, name: date, widget: datetime }
          - { label: Sponsor 01 - Name, name: sponsorName01, required: false, widget: text, default: "" }
          - { label: Sponsor 01 - Image, name: sponsorImage01, required: false, widget: image, default: "" }
          - { label: Sponsor 01 - URL, name: sponsorUrl01, hint: "full URL including http:// or https://", required: false, widget: text, default: "" }
          - { label: Sponsor 01 - Text, name: sponsorText01, required: false, hint: "Brief description", widget: text, default: "" }
          - { label: Sponsor 02 - Name, name: sponsorName02, required: false, widget: text, default: "" }
          - { label: Sponsor 02 - Image, name: sponsorImage02, required: false, widget: image, default: "" }
          - { label: Sponsor 02 - URL, name: sponsorUrl02, hint: "full URL including http:// or https://", required: false, widget: text, default: "" }
          - { label: Sponsor 02 - Text, name: sponsorText02, required: false, hint: "Brief description", widget: text, default: "" }
          - { label: Sponsor 03 - Name, name: sponsorName03, required: false, widget: text, default: "" }
          - { label: Sponsor 03 - Image, name: sponsorImage03, required: false, widget: image, default: "" }
          - { label: Sponsor 03 - URL, name: sponsorUrl03, hint: "full URL including http:// or https://", required: false, widget: text, default: "" }
          - { label: Sponsor 03 - Text, name: sponsorText03, required: false, hint: "Brief description", widget: text, default: "" }
          - { label: Sponsor 04 - Name, name: sponsorName04, required: false, widget: text, default: "" }
          - { label: Sponsor 04 - Image, name: sponsorImage04, required: false, widget: image, default: "" }
          - { label: Sponsor 04 - URL, name: sponsorUrl04, hint: "full URL including http:// or https://", required: false, widget: text, default: "" }
          - { label: Sponsor 04 - Text, name: sponsorText04, required: false, hint: "Brief description", widget: text, default: "" }
          - { label: Sponsor 05 - Name, name: sponsorName05, required: false, widget: text, default: "" }
          - { label: Sponsor 05 - Image, name: sponsorImage05, required: false, widget: image, default: "" }
          - { label: Sponsor 05 - URL, name: sponsorUrl05, hint: "full URL including http:// or https://", required: false, widget: text, default: "" }
          - { label: Sponsor 05 - Text, name: sponsorText05, required: false, hint: "Brief description", widget: text, default: "" }
          - { label: Sponsor 06 - Name, name: sponsorName06, required: false, widget: text, default: "" }
          - { label: Sponsor 06 - Image, name: sponsorImage06, required: false, widget: image, default: "" }
          - { label: Sponsor 06 - URL, name: sponsorUrl06, hint: "full URL including http:// or https://", required: false, widget: text, default: "" }
          - { label: Sponsor 06 - Text, name: sponsorText06, required: false, hint: "Brief description", widget: text, default: "" }
          - { label: Sponsor 07 - Name, name: sponsorName07, required: false, widget: text, default: "" }
          - { label: Sponsor 07 - Image, name: sponsorImage07, required: false, widget: image, default: "" }
          - { label: Sponsor 07 - URL, name: sponsorUrl07, hint: "full URL including http:// or https://", required: false, widget: text, default: "" }
          - { label: Sponsor 07 - Text, name: sponsorText07, required: false, hint: "Brief description", widget: text, default: "" }
          - { label: Sponsor 08 - Name, name: sponsorName08, required: false, widget: text, default: "" }
          - { label: Sponsor 08 - Image, name: sponsorImage08, required: false, widget: image, default: "" }
          - { label: Sponsor 08 - URL, name: sponsorUrl08, hint: "full URL including http:// or https://", required: false, widget: text, default: "" }
          - { label: Sponsor 08 - Text, name: sponsorText08, required: false, hint: "Brief description", widget: text, default: "" }
          - { label: Sponsor 09 - Name, name: sponsorName09, required: false, widget: text, default: "" }
          - { label: Sponsor 09 - Image, name: sponsorImage09, required: false, widget: image, default: "" }
          - { label: Sponsor 09 - URL, name: sponsorUrl09, hint: "full URL including http:// or https://", required: false, widget: text, default: "" }
          - { label: Sponsor 09 - Text, name: sponsorText09, required: false, hint: "Brief description", widget: text, default: "" }
          - { label: Sponsor 10 - Name, name: sponsorName10, required: false, widget: text, default: "" }
          - { label: Sponsor 10 - Image, name: sponsorImage10, required: false, widget: image, default: "" }
          - { label: Sponsor 10 - URL, name: sponsorUrl10, hint: "full URL including http:// or https://", required: false, widget: text, default: "" }
          - { label: Sponsor 10 - Text, name: sponsorText10, required: false, hint: "Brief description", widget: text, default: "" }
          - { label: Sponsor 11 - Name, name: sponsorName11, required: false, widget: text, default: "" }
          - { label: Sponsor 11 - Image, name: sponsorImage11, required: false, widget: image, default: "" }
          - { label: Sponsor 11 - URL, name: sponsorUrl11, hint: "full URL including http:// or https://", required: false, widget: text, default: "" }
          - { label: Sponsor 11 - Text, name: sponsorText11, required: false, hint: "Brief description", widget: text, default: "" }
          - { label: Sponsor 12 - Name, name: sponsorName12, required: false, widget: text, default: "" }
          - { label: Sponsor 12 - Image, name: sponsorImage12, required: false, widget: image, default: "" }
          - { label: Sponsor 12 - URL, name: sponsorUrl12, hint: "full URL including http:// or https://", required: false, widget: text, default: "" }
          - { label: Sponsor 12 - Text, name: sponsorText12, required: false, hint: "Brief description", widget: text, default: "" }
          - { label: Sponsor 13 - Name, name: sponsorName13, required: false, widget: text, default: "" }
          - { label: Sponsor 13 - Image, name: sponsorImage13, required: false, widget: image, default: "" }
          - { label: Sponsor 13 - URL, name: sponsorUrl13, hint: "full URL including http:// or https://", required: false, widget: text, default: "" }
          - { label: Sponsor 13 - Text, name: sponsorText13, required: false, hint: "Brief description", widget: text, default: "" }
          - { label: Sponsor 14 - Name, name: sponsorName14, required: false, widget: text, default: "" }
          - { label: Sponsor 14 - Image, name: sponsorImage14, required: false, widget: image, default: "" }
          - { label: Sponsor 14 - URL, name: sponsorUrl14, hint: "full URL including http:// or https://", required: false, widget: text, default: "" }
          - { label: Sponsor 14 - Text, name: sponsorText14, required: false, hint: "Brief description", widget: text, default: "" }

  - name: pages
    label: Pages
    files:
      - label: Home Page
        name: home
        file: "content/home/home.md"
        fields:
          - { label: Template Key, name: templateKey, widget: hidden, default: home-page }
          - { label: Title, name: title, widget: string }
          - { label: Date, name: date, widget: datetime }
          - { label: Alert Headline, name: alertheadline, required: false, widget: markdown }
          - { label: Alert Subhead, name: alertsub, required: false, widget: text }

  - name: alert
    label: Alerts
    files:
      - label: Alert Main
        name: alertMain
        file: "content/alerts/alert-main.md"
        fields:
          - { label: Template Key, name: templateKey, widget: hidden, default: alert-main }
          - { label: Title, name: title, widget: string }
          - { label: Date, name: date, widget: datetime }
          - { label: Enable Alert, name: enabled, widget: boolean, default: true }
          - { label: Display on all pages, name: allPages, widget: boolean, hint: Displays only on Home Page by default, default: false }
          - { label: Body, name: body, required: false, widget: markdown }