backend: 
  name: git-gateway
  branch: master
  commit_messages:
    create: 'Create {{collection}} “{{slug}}”'
    update: 'Update {{collection}} “{{slug}}”'
    delete: 'Delete {{collection}} “{{slug}}”'
    uploadMedia: '[skip ci] Upload “{{path}}”'
    deleteMedia: '[skip ci] Delete “{{path}}”'

media_folder: content/media
public_folder: ../media

media_library:
  name: cloudinary
  config:
    cloud_name: drgctrdk4
    api_key: 855765796578929

collections:
  - name: posts
    label: News
    folder: content/news
    create: true
    fields:
      - { name: "templateKey", label: "Template Key", widget: "hidden", default: "news-post" }
      - { name: title, label: Title }
      - { name: date, label: Date, widget: datetime }
      - { name: text1, label: Text Field, required: false, widget: markdown }
      - { name: text2, label: Text Field, required: false, widget: markdown }
      - { name: image1, label: Image, required: false, widget: image }
      - { name: text3, label: Text Field, required: false, widget: markdown }
      - { name: text4, label: Text Field, required: false, widget: markdown }
      - { name: body, label: Body, required: false, widget: markdown }

  - name: pages
    label: Pages
    files:
      - label: Home Page
        name: home
        file: "content/home/home.md"
        fields:
          - { label: "Template Key", name: "templateKey", widget: "hidden", default: "home-page" }
          - { label: Title, name: title, widget: string }
          - { label: Date, name: date, widget: datetime }
          - { label: Alert Headline, name: alertheadline, required: false, widget: markdown }
          - { label: Alert Subhead, name: alertsub, required: false, widget: text }