backend: 
  name: git-gateway
  branch: master

media_folder: content/media
public_folder: /media

collections:
  - name: posts
    label: News
    folder: content/news
    create: true
    fields:
      - { name: "templateKey", label: "Template Key", widget: "hidden", default: "news-post" }
      - { name: title, label: Title }
      - { name: date, label: Date, widget: datetime }
      - { name: image, label: Image, widget: image }
      - { name: body, label: Body, widget: markdown }

  - name: pages
    label: Pages
    files:
      - label: Home Page
        name: home
        file: "content/home/home.md"
        fields:
          - { label: "Template Key", name: "templateKey", widget: "hidden", default: "home-page" }
          - { label: Title, name: title, widget: string }
          - { label: Date, name: date, widget: datetime }
          - { label: Alert Headline, name: alertheadline, widget: markdown }
          - { label: Alert Subhead, name: alertsub, widget: text }